{"message":"C:\\Users\\ericm\\Desktop\\conexusFinal\\prj-final-front-back-g1-conexus\\back\\node\\services\\notifications\\index.js:8\r\nconst path = require('path');\r\n      ^\r\n\r\nSyntaxError: Identifier 'path' has already been declared\r\n    at internalCompileFunction (node:internal/vm:77:18)\r\n    at wrapSafe (node:internal/modules/cjs/loader:1288:20)\r\n    at Module._compile (node:internal/modules/cjs/loader:1340:27)\r\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\r\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)\r\n    at node:internal/main/run_main_module:28:49\r\n","timestamp":"23/01/2025 12:21:49"}
{"message":"\r\nNode.js v20.11.1\r\n","timestamp":"23/01/2025 12:21:49"}
{"message":"C:\\Users\\ericm\\Desktop\\conexusFinal\\prj-final-front-back-g1-conexus\\back\\node\\services\\notifications\\index.js:8\r\nconst path = require('path');\r\n      ^\r\n\r\nSyntaxError: Identifier 'path' has already been declared\r\n    at internalCompileFunction (node:internal/vm:77:18)\r\n    at wrapSafe (node:internal/modules/cjs/loader:1288:20)\r\n    at Module._compile (node:internal/modules/cjs/loader:1340:27)\r\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\r\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)\r\n    at node:internal/main/run_main_module:28:49\r\n\r\nNode.js v20.11.1\r\n","timestamp":"23/01/2025 12:22:03"}
{"message":"node:events:496\r\n      throw er; // Unhandled 'error' event\r\n      ^\r\n\r\nError: listen EADDRINUSE: address already in use :::3006\r\n    at Server.setupListenHandle [as _listen2] (node:net:1872:16)\r\n    at listenInCluster (node:net:1920:12)\r\n    at Server.listen (node:net:2008:7)\r\n    at Function.listen (C:\\Users\\ericm\\Desktop\\conexusFinal\\prj-final-front-back-g1-conexus\\back\\node\\services\\notifications\\node_modules\\express\\lib\\application.js:635:24)\r\n    at Object.<anonymous> (C:\\Users\\ericm\\Desktop\\conexusFinal\\prj-final-front-back-g1-conexus\\back\\node\\services\\notifications\\index.js:148:5)\r\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\r\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\r\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)\r\nEmitted 'error' event on Server instance at:\r\n    at emitErrorNT (node:net:1899:8)\r\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {\r\n  code: 'EADDRINUSE',\r\n  errno: -4091,\r\n  syscall: 'listen',\r\n  address: '::',\r\n  port: 3006\r\n}\r\n\r\nNode.js v20.11.1\r\n","timestamp":"23/01/2025 12:23:35"}
{"message":"node:events:496\r\n      throw er; // Unhandled 'error' event\r\n      ^\r\n\r\nError: listen EADDRINUSE: address already in use :::3006\r\n    at Server.setupListenHandle [as _listen2] (node:net:1872:16)\r\n    at listenInCluster (node:net:1920:12)\r\n    at Server.listen (node:net:2008:7)\r\n    at Function.listen (C:\\Users\\ericm\\Desktop\\conexusFinal\\prj-final-front-back-g1-conexus\\back\\node\\services\\notifications\\node_modules\\express\\lib\\application.js:635:24)\r\n    at Object.<anonymous> (C:\\Users\\ericm\\Desktop\\conexusFinal\\prj-final-front-back-g1-conexus\\back\\node\\services\\notifications\\index.js:148:5)\r\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\r\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\r\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)\r\nEmitted 'error' event on Server instance at:\r\n    at emitErrorNT (node:net:1899:8)\r\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {\r\n  code: 'EADDRINUSE',\r\n  errno: -4091,\r\n  syscall: 'listen',\r\n  address: '::',\r\n  port: 3006\r\n}\r\n\r\nNode.js v20.11.1\r\n","timestamp":"23/01/2025 12:23:49"}
